import java.util.Arrays;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  static List<String> Names;
  static int Years;

  public static void main(String[] args) {
    parseArgs(args);
    List<String> participants = validatedParticipants(Names);
    SecretSanta secretSanta = new SecretSanta();

    for (int i = 0; i < Years; i++) {
      List<String> assignments = secretSanta.generateAssignments(participants, i);
      secretSanta.printResults(participants, assignments, i + 1);
    }
  }
  /**
   * @param args
   *          arguments passed to program
   */

  public static void parseArgs(String[] args) {
    String[] list = args[0].split("/");
    Names = Arrays.asList(list[0].split(" "));
    try {
      Years = Integer.parseInt(list[1]);

      if (Years < 1) {
        throw new java.lang.Error("Please enter a number of at least 1");
      }
    } catch (NumberFormatException e) {
      throw new java.lang.Error("Please enter valid number for years");
    }
  };

  /**
   * @param names
   *          even number of names, space separated
   */
  public static List<String> validatedParticipants(List<String> names) {
    if (names.size() == 0) {
      throw new java.lang.Error("Please enter some names");
    }

    if (names.size() % 2 > 0) {
      throw new java.lang.Error("Please enter an even number of names");
    }
    return names;
  }
}